package Sprint1;
/* Generated By:JavaCC: Do not edit this line. LexerGrupo3Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LexerGrupo3Constants {

    /** End of File. */
    int EOF = 0;
    /** RegularExpression Id. */
    int LOAD = 1;
    /** RegularExpression Id. */
    int LOADIM = 2;
    /** RegularExpression Id. */
    int POP = 3;
    /** RegularExpression Id. */
    int STORE = 4;
    /** RegularExpression Id. */
    int PUSH = 5;
    /** RegularExpression Id. */
    int LOADRIND = 6;
    /** RegularExpression Id. */
    int STORERIND = 7;
    /** RegularExpression Id. */
    int ADD = 8;
    /** RegularExpression Id. */
    int SUB = 9;
    /** RegularExpression Id. */
    int ADDIM = 10;
    /** RegularExpression Id. */
    int SUBIM = 11;
    /** RegularExpression Id. */
    int AND = 12;
    /** RegularExpression Id. */
    int OR = 13;
    /** RegularExpression Id. */
    int XOR = 14;
    /** RegularExpression Id. */
    int NOT = 15;
    /** RegularExpression Id. */
    int NEG = 16;
    /** RegularExpression Id. */
    int SHIFTR = 17;
    /** RegularExpression Id. */
    int SHIFTL = 18;
    /** RegularExpression Id. */
    int ROTAR = 19;
    /** RegularExpression Id. */
    int ROTAL = 20;
    /** RegularExpression Id. */
    int JMPRIND = 21;
    /** RegularExpression Id. */
    int JMPADDR = 22;
    /** RegularExpression Id. */
    int JCONDRIN = 23;
    /** RegularExpression Id. */
    int JCONDADDR = 24;
    /** RegularExpression Id. */
    int LOOP = 25;
    /** RegularExpression Id. */
    int GRT = 26;
    /** RegularExpression Id. */
    int GRTEQ = 27;
    /** RegularExpression Id. */
    int EQ = 28;
    /** RegularExpression Id. */
    int NEQ = 29;
    /** RegularExpression Id. */
    int NOP = 30;
    /** RegularExpression Id. */
    int CALL = 31;
    /** RegularExpression Id. */
    int RETURN = 32;
    /** RegularExpression Id. */
    int ORG = 33;
    /** RegularExpression Id. */
    int DB = 34;
    /** RegularExpression Id. */
    int CONST = 35;
    /** RegularExpression Id. */
    int COMMENT = 36;
    /** RegularExpression Id. */
    int COMMA = 37;
    /** RegularExpression Id. */
    int LABEL = 38;
    /** RegularExpression Id. */
    int HEX = 39;
    /** RegularExpression Id. */
    int MSPACE = 40;
    /** RegularExpression Id. */
    int SPACE = 41;
    /** RegularExpression Id. */
    int TSPACE = 42;
    /** RegularExpression Id. */
    int INMEDIATE = 43;
    /** RegularExpression Id. */
    int REGISTER = 44;
    /** RegularExpression Id. */
    int VARIABLE = 45;
    /** RegularExpression Id. */
    int INTEGER = 46;
    /** RegularExpression Id. */
    int LETTER = 47;
    /** RegularExpression Id. */
    int REGNUMBER = 48;
    /** RegularExpression Id. */
    int HEXNUM = 49;
    /** RegularExpression Id. */
    int SYMBOLS = 50;
    /** RegularExpression Id. */
    int ACENTOS = 51;

    /** Lexical state. */
    int DEFAULT = 0;

    /** Literal token values. */
    String[] tokenImage = {
            "<EOF>",
            "\"LOAD\"",
            "\"LOADIM\"",
            "\"POP\"",
            "\"STORE\"",
            "\"PUSH\"",
            "\"LOADRIND\"",
            "\"STORERIND\"",
            "\"ADD\"",
            "\"SUB\"",
            "\"ADDIM\"",
            "\"SUBIM\"",
            "\"AND\"",
            "\"OR\"",
            "\"XOR\"",
            "\"NOT\"",
            "\"NEG\"",
            "\"SHIFTR\"",
            "\"SHIFTL\"",
            "\"ROTAR\"",
            "\"ROTAL\"",
            "\"JMPRIND\"",
            "\"JMPADDR\"",
            "\"JCONDRIN\"",
            "\"JCONDADDR\"",
            "\"LOOP\"",
            "\"GRT\"",
            "\"GRTEQ\"",
            "\"EQ\"",
            "\"NEQ\"",
            "\"NOP\"",
            "\"CALL\"",
            "\"RETURN\"",
            "\"ORG\"",
            "\"DB\"",
            "\"CONST\"",
            "<COMMENT>",
            "\",\"",
            "<LABEL>",
            "<HEX>",
            "<MSPACE>",
            "<SPACE>",
            "<TSPACE>",
            "<INMEDIATE>",
            "<REGISTER>",
            "<VARIABLE>",
            "<INTEGER>",
            "<LETTER>",
            "<REGNUMBER>",
            "<HEXNUM>",
            "<SYMBOLS>",
            "<ACENTOS>",
    };

}
