/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Sprint1.TestFormNuestro;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.JFileChooser;
import javax.swing.text.*;


/**
 *
 * @author christianmalave
 */
public class GUI extends javax.swing.JFrame {

	/**
	 * Creates new form GUI
	 */
	public GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		Main main;


		R0field = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		R1field = new javax.swing.JTextField();
		R2field = new javax.swing.JTextField();
		R3field = new javax.swing.JTextField();
		R4field = new javax.swing.JTextField();
		R5field = new javax.swing.JTextField();
		R6field = new javax.swing.JTextField();
		R7field = new javax.swing.JTextField();
		Condfield = new javax.swing.JTextField();
		R0 = new javax.swing.JLabel();
		R1 = new javax.swing.JLabel();
		R2 = new javax.swing.JLabel();
		R3 = new javax.swing.JLabel();
		R4 = new javax.swing.JLabel();
		R5 = new javax.swing.JLabel();
		R6 = new javax.swing.JLabel();
		R7 = new javax.swing.JLabel();
		Cond = new javax.swing.JLabel();
		PDfield = new javax.swing.JTextField();
		SPfield = new javax.swing.JTextField();
		IRfield = new javax.swing.JTextField();
		PC = new javax.swing.JLabel();
		SP = new javax.swing.JLabel();
		IR = new javax.swing.JLabel();
		Instrucdisplay = new javax.swing.JTextField();
		NextLineButton = new javax.swing.JButton();
		GoButton = new javax.swing.JButton();
		AsciiPanel = new javax.swing.JPanel();
		Hex1 = new javax.swing.JTextField();
		Hex2 = new javax.swing.JTextField();
		Hex3 = new javax.swing.JTextField();
		Hex4 = new javax.swing.JTextField();
		Hex5 = new javax.swing.JTextField();
		Hex6 = new javax.swing.JTextField();
		Hex7 = new javax.swing.JTextField();
		Hex8 = new javax.swing.JTextField();
		KeyboardPanel = new javax.swing.JPanel();
		Button0 = new javax.swing.JButton();
		Button1 = new javax.swing.JButton();
		Button2 = new javax.swing.JButton();
		Button3 = new javax.swing.JButton();
		Button4 = new javax.swing.JButton();
		Button5 = new javax.swing.JButton();
		Button6 = new javax.swing.JButton();
		Button7 = new javax.swing.JButton();
		Button8 = new javax.swing.JButton();
		Button9 = new javax.swing.JButton();
		ButtonA = new javax.swing.JButton();
		ButtonB = new javax.swing.JButton();
		ButtonC = new javax.swing.JButton();
		ButtonD = new javax.swing.JButton();
		ButtonE = new javax.swing.JButton();
		ButtonF = new javax.swing.JButton();
		SegmentPanel = new javax.swing.JPanel();
		Seg0A = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
		Seg0B = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg0F = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg0G = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
		Seg0E = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg0D = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
		Seg0C = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg1F = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg1G = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
		Seg1E = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg1D = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
		Seg1C = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Seg1A = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
		Seg1B = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
		Semaforo0Panel = new javax.swing.JPanel();
		Red0 = new javax.swing.JLabel();
		Yellow0 = new javax.swing.JLabel();
		Green0 = new javax.swing.JLabel();
		Semaforo1Panel = new javax.swing.JPanel();
		Red3 = new javax.swing.JLabel();
		Yellow3 = new javax.swing.JLabel();
		Green3 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenuFile = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jmenuRun = new javax.swing.JMenu();
		jMenuSaveState = new javax.swing.JMenuItem();
		JMenuItem jMenuSave = new JMenuItem();
		JMenuItem jMenuLoad = new JMenuItem();
		SelectMSG = new javax.swing.JLabel();
		IOPop = new JMenuItem();
		Run = new JMenuItem();

		jmenuView = new javax.swing.JMenu();
		jCheckBoxMenuKeyboard = new javax.swing.JCheckBoxMenuItem();
		jCheckBoxMenuKeyboard.setState(true);
		jCheckBoxMenuASCII = new javax.swing.JCheckBoxMenuItem();
		jCheckBoxMenuASCII.setState(true);
		jCheckBoxMenuSemaforo = new javax.swing.JCheckBoxMenuItem();
		jCheckBoxMenuSemaforo.setState(true);
		jCheckBoxMenuSegmentDisp = new javax.swing.JCheckBoxMenuItem();
		jCheckBoxMenuSegmentDisp.setState(true);


		String RIcon = "/58afdad6829958a978a4a693.png";
		String YIcon = "/Yellow_icon.svg.png";
		String GIcon = "/600px-Ski_trail_rating_symbol-green_circle.svg.png";
		String BIcon = "/Solid_black.png";

		jPanel1 = new javax.swing.JPanel();
		TextPanel = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		jEditorPane1 = new javax.swing.JEditorPane();
		StyleContext styleContext = new StyleContext();
		Style defaultStyle = styleContext.getStyle(StyleContext.DEFAULT_STYLE);
		Style cwStyle = styleContext.addStyle("ConstantWidth", null);
		StyleConstants.setForeground(cwStyle, Color.BLUE);
		StyleConstants.setBold(cwStyle, true);
		jTextPane1 = new javax.swing.JTextPane(new KeywordStyledDocument(defaultStyle, cwStyle));

		fileChooser = new JFileChooser();
		fileChooser.setFileFilter(new MyCustomFilter());

		JFrame parentFrame = new JFrame();
		SaveFile = new JFileChooser();
		SaveFile.setDialogTitle("Save");

		jDialogIOSettings = new javax.swing.JDialog();
		DSemaforo = new javax.swing.JLabel();
		DSegment = new javax.swing.JLabel();
		DAscii = new javax.swing.JLabel();
		DKeyboard = new javax.swing.JLabel();
		DGoIter = new javax.swing.JLabel();
		jSpinnerSemaforo = new javax.swing.JSpinner();
		jSpinnerSegment = new javax.swing.JSpinner();
		jSpinnerAscii = new javax.swing.JSpinner();
		jSpinnerKeyboard = new javax.swing.JSpinner();
		jSpinnerGoIter = new javax.swing.JSpinner();
		DialButtonSelect = new javax.swing.JButton();
		DialButtonCancel = new javax.swing.JButton();




		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		setResizable(false);
		setSize(new java.awt.Dimension(1024, 650));

		R0field.setText("R0!");
		R0field.setEditable(false);

		int counter = 0;
		for (int i=0; i<4096; i++)
			Data[i][0]=Integer.toHexString(i).toUpperCase();
		for (int i=0; i<2048; i++)
			DataXInst[i][0] = Integer.toHexString((i*2)).toUpperCase();
		for (int i=0; i<2048; i++)
			DataXInst[i][1] = "0000";

		for (int i=0; i<4096; i++)
			Data[i][1] = "00";

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				DataXInst,
				new String [] {
						"Direccion", "Contenido"
				}
		));
		jScrollPane2.setViewportView(jTable1);

		R1field.setText("R1!");
		R1field.setEditable(false);

		R2field.setText("R2!");
		R2field.setEditable(false);

		R3field.setText("R3!");
		R3field.setEditable(false);

		R4field.setText("R4!");
		R4field.setEditable(false);

		R5field.setText("R5!");
		R5field.setEditable(false);

		R6field.setText("R6!");
		R6field.setEditable(false);

		R7field.setText("R7!");
		R7field.setEditable(false);

		Condfield.setText("Cond!");
		Condfield.setEditable(false);

		R0.setText("R0");

		R1.setText("R1");

		R2.setText("R2");

		R3.setText("R3");

		R4.setText("R4");

		R5.setText("R5");

		R6.setText("R6");

		R7.setText("R7");

		Cond.setText("Cond");

		PDfield.setText("PC!");
		PDfield.setEditable(false);

		SPfield.setText("SP!");
		SPfield.setEditable(false);

		IRfield.setText("IR!");
		IRfield.setEditable(false);

		PC.setText("PC");

		SP.setText("SP");

		IR.setText("IR");

		Instrucdisplay.setText("INSTRUCTION!");
		Instrucdisplay.setEditable(false);

		NextLineButton.setText("Next Line");

		GoButton.setText("GO!");

		jMenuFile.setText("File");
		jMenuBar1.add(jMenuFile);

		jMenuSave.setText("Save");
		jMenuLoad.setText("Load");
		jMenuSaveState.setText("Save State");


		GoButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				GOActionPerformed(evt);
				}
		});
		NextLineButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				NextLineActionPerformed(evt);
			}
		});

		jMenuSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuSaveActionPerformed(evt);
			}
		});

		jMenuLoad.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuLoadActionPerformed(evt);
			}
		});
		jMenuSaveState.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SaveStateActionPerformed(evt);
			}
		});

		/************HexKeyboard****************************************************/
		Button0.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button0ActionPerformed(evt);
			}
		});
		Button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button1ActionPerformed(evt);
			}
		});
		Button2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button2ActionPerformed(evt);
			}
		});
		Button3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button3ActionPerformed(evt);
			}
		});
		Button4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button4ActionPerformed(evt);
			}
		});
		Button5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button5ActionPerformed(evt);
			}
		});
		Button6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button6ActionPerformed(evt);
			}
		});
		Button7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button7ActionPerformed(evt);
			}
		});
		Button8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button8ActionPerformed(evt);
			}
		});
		Button9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Button9ActionPerformed(evt);
			}
		});
		ButtonA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonAActionPerformed(evt);
			}
		});
		ButtonB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonBActionPerformed(evt);
			}
		});
		ButtonC.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonCActionPerformed(evt);
			}
		});
		ButtonD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonDActionPerformed(evt);
			}
		});
		ButtonE.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonEActionPerformed(evt);
			}
		});
		ButtonF.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ButtonFActionPerformed(evt);
			}
		});




		jMenuFile.add(jMenuLoad);
		jMenuFile.add(jMenuSave);
		jMenuFile.add(jMenuSaveState);//FALTA CREAR EL ACTIONLISTENER




		Run.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RunActionPerformed(evt);
			}
		});

		IOPop.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				IOPopActionPerformed(evt);
			}
		});





		AsciiPanel.setBackground(new java.awt.Color(102, 102, 102));


		Hex1.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex1.setText("A");

		Hex2.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex2.setText("B");

		Hex3.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex3.setText("C");

		Hex4.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex4.setText("B");

		Hex5.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex5.setText("F");

		Hex6.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex6.setText("F");

		Hex7.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex7.setText("G");

		Hex8.setFont(new java.awt.Font("Monaco", 1, 48)); // NOI18N
		Hex8.setText("H");



		javax.swing.GroupLayout AsciiPanelLayout = new javax.swing.GroupLayout(AsciiPanel);
		AsciiPanel.setLayout(AsciiPanelLayout);
		AsciiPanelLayout.setHorizontalGroup(
				AsciiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(AsciiPanelLayout.createSequentialGroup()
								.addContainerGap()
								.addComponent(Hex1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Hex2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Hex3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Hex4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Hex5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Hex6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(Hex7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(Hex8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap())
		);
		AsciiPanelLayout.setVerticalGroup(
				AsciiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(AsciiPanelLayout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE)
								.addGroup(AsciiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsciiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Hex3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Hex4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Hex5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Hex6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Hex7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Hex8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AsciiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(Hex1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(Hex2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
		);

		KeyboardPanel.setBackground(new java.awt.Color(102, 102, 102));

		Button0.setFont(new java.awt.Font("Lucida Grande", 0, 12));
		Button0.setText("0");

		Button1.setText("1");

		Button2.setText("2");

		Button3.setText("3");

		Button4.setText("4");

		Button5.setText("5");

		Button6.setText("6");

		Button7.setText("7");

		Button8.setText("8");

		Button9.setText("9");

		ButtonA.setText("A");

		ButtonB.setText("B");

		ButtonC.setText("C");

		ButtonD.setText("D");

		ButtonE.setText("E");

		ButtonF.setText("F");

		javax.swing.GroupLayout KeyboardPanelLayout = new javax.swing.GroupLayout(KeyboardPanel);
		KeyboardPanel.setLayout(KeyboardPanelLayout);
		KeyboardPanelLayout.setHorizontalGroup(
				KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(KeyboardPanelLayout.createSequentialGroup()
								.addContainerGap()
								.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(KeyboardPanelLayout.createSequentialGroup()
												.addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(KeyboardPanelLayout.createSequentialGroup()
												.addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(KeyboardPanelLayout.createSequentialGroup()
												.addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(ButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(ButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(KeyboardPanelLayout.createSequentialGroup()
												.addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(ButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		KeyboardPanelLayout.setVerticalGroup(
				KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(KeyboardPanelLayout.createSequentialGroup()
								.addContainerGap()
								.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(Button0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(KeyboardPanelLayout.createSequentialGroup()
												.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(ButtonA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(ButtonB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(ButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(KeyboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(ButtonF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(ButtonE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(ButtonD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		SegmentPanel.setBackground(new java.awt.Color(0, 0, 0));

		Seg0A.setBackground(new java.awt.Color(255, 0, 0));
		Seg0A.setForeground(new java.awt.Color(255, 0, 0));
		Seg0A.setOpaque(true);

		Seg0B.setBackground(new java.awt.Color(255, 0, 0));
		Seg0B.setForeground(new java.awt.Color(255, 0, 0));
		Seg0B.setOpaque(true);

		Seg0F.setBackground(new java.awt.Color(255, 0, 0));
		Seg0F.setForeground(new java.awt.Color(255, 0, 0));
		Seg0F.setOpaque(true);

		Seg0G.setBackground(new java.awt.Color(255, 0, 0));
		Seg0G.setForeground(new java.awt.Color(255, 0, 0));
		Seg0G.setOpaque(true);

		Seg0E.setBackground(new java.awt.Color(255, 0, 0));
		Seg0E.setForeground(new java.awt.Color(255, 0, 0));
		Seg0E.setOpaque(true);

		Seg0D.setBackground(new java.awt.Color(255, 0, 0));
		Seg0D.setForeground(new java.awt.Color(255, 0, 0));
		Seg0D.setOpaque(true);

		Seg0C.setBackground(new java.awt.Color(255, 0, 0));
		Seg0C.setForeground(new java.awt.Color(255, 0, 0));
		Seg0C.setOpaque(true);

		Seg1F.setBackground(new java.awt.Color(255, 0, 0));
		Seg1F.setForeground(new java.awt.Color(255, 0, 0));
		Seg1F.setOpaque(true);

		Seg1G.setBackground(new java.awt.Color(255, 0, 0));
		Seg1G.setForeground(new java.awt.Color(255, 0, 0));
		Seg1G.setOpaque(true);

		Seg1E.setBackground(new java.awt.Color(255, 0, 0));
		Seg1E.setForeground(new java.awt.Color(255, 0, 0));
		Seg1E.setOpaque(true);

		Seg1D.setBackground(new java.awt.Color(255, 0, 0));
		Seg1D.setForeground(new java.awt.Color(255, 0, 0));
		Seg1D.setOpaque(true);

		Seg1C.setBackground(new java.awt.Color(255, 0, 0));
		Seg1C.setForeground(new java.awt.Color(255, 0, 0));
		Seg1C.setOpaque(true);

		Seg1A.setBackground(new java.awt.Color(255, 0, 0));
		Seg1A.setForeground(new java.awt.Color(255, 0, 0));
		Seg1A.setOpaque(true);

		Seg1B.setBackground(new java.awt.Color(255, 0, 0));
		Seg1B.setForeground(new java.awt.Color(255, 0, 0));
		Seg1B.setOpaque(true);

		javax.swing.GroupLayout SegmentPanelLayout = new javax.swing.GroupLayout(SegmentPanel);
		SegmentPanel.setLayout(SegmentPanelLayout);
		SegmentPanelLayout.setHorizontalGroup(
				SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(SegmentPanelLayout.createSequentialGroup()
								.addGap(14, 14, 14)
								.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(SegmentPanelLayout.createSequentialGroup()
												.addGap(10, 10, 10)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Seg0G, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Seg0A, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegmentPanelLayout.createSequentialGroup()
																.addComponent(Seg0E, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(28, 28, 28)
																.addComponent(Seg0C, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(SegmentPanelLayout.createSequentialGroup()
																.addGap(10, 10, 10)
																.addComponent(Seg0D, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(SegmentPanelLayout.createSequentialGroup()
														.addComponent(Seg0F, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(28, 28, 28)
														.addComponent(Seg0B, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
								.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(SegmentPanelLayout.createSequentialGroup()
												.addGap(10, 10, 10)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Seg1G, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Seg1A, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SegmentPanelLayout.createSequentialGroup()
																.addComponent(Seg1E, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(28, 28, 28)
																.addComponent(Seg1C, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(SegmentPanelLayout.createSequentialGroup()
																.addGap(10, 10, 10)
																.addComponent(Seg1D, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(SegmentPanelLayout.createSequentialGroup()
														.addComponent(Seg1F, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(28, 28, 28)
														.addComponent(Seg1B, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(28, 28, 28))
		);
		SegmentPanelLayout.setVerticalGroup(
				SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(SegmentPanelLayout.createSequentialGroup()
								.addGap(15, 15, 15)
								.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(SegmentPanelLayout.createSequentialGroup()
												.addComponent(Seg1A, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Seg1B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Seg1F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(4, 4, 4)
												.addComponent(Seg1G, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Seg1C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Seg1E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(4, 4, 4)
												.addComponent(Seg1D, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(SegmentPanelLayout.createSequentialGroup()
												.addComponent(Seg0A, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Seg0B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Seg0F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(4, 4, 4)
												.addComponent(Seg0G, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(SegmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Seg0C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Seg0E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(4, 4, 4)
												.addComponent(Seg0D, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		Semaforo0Panel.setBackground(new java.awt.Color(0, 0, 0));

		Red0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/58afdad6829958a978a4a693.png"))); // NOI18N

		Yellow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_icon.svg.png"))); // NOI18N

		Green0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/600px-Ski_trail_rating_symbol-green_circle.svg.png"))); // NOI18N

		javax.swing.GroupLayout Semaforo0PanelLayout = new javax.swing.GroupLayout(Semaforo0Panel);
		Semaforo0Panel.setLayout(Semaforo0PanelLayout);
		Semaforo0PanelLayout.setHorizontalGroup(
				Semaforo0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(Semaforo0PanelLayout.createSequentialGroup()
								.addContainerGap()
								.addGroup(Semaforo0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(Red0)
										.addComponent(Yellow0)
										.addComponent(Green0))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		Semaforo0PanelLayout.setVerticalGroup(
				Semaforo0PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(Semaforo0PanelLayout.createSequentialGroup()
								.addGap(14, 14, 14)
								.addComponent(Red0)
								.addGap(26, 26, 26)
								.addComponent(Yellow0)
								.addGap(26, 26, 26)
								.addComponent(Green0)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		Semaforo1Panel.setBackground(new java.awt.Color(0, 0, 0));

		Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/58afdad6829958a978a4a693.png"))); // NOI18N

		Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_icon.svg.png"))); // NOI18N

		Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/600px-Ski_trail_rating_symbol-green_circle.svg.png"))); // NOI18N

		javax.swing.GroupLayout Semaforo1PanelLayout = new javax.swing.GroupLayout(Semaforo1Panel);
		Semaforo1Panel.setLayout(Semaforo1PanelLayout);
		Semaforo1PanelLayout.setHorizontalGroup(
				Semaforo1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(Semaforo1PanelLayout.createSequentialGroup()
								.addContainerGap()
								.addGroup(Semaforo1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(Red3)
										.addComponent(Yellow3)
										.addComponent(Green3))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		Semaforo1PanelLayout.setVerticalGroup(
				Semaforo1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(Semaforo1PanelLayout.createSequentialGroup()
								.addGap(14, 14, 14)
								.addComponent(Red3)
								.addGap(26, 26, 26)
								.addComponent(Yellow3)
								.addGap(26, 26, 26)
								.addComponent(Green3)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		TextPanel.setViewportView(jTextPane1);


		/**********************************************************************************/

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(TextPanel)
		);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(TextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
		);

		/****************************Menu bar Setup********************************************************************/
		setJMenuBar(jMenuBar1);

		jMenuFile.setText("File");
		jMenuBar1.add(jMenuFile);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);


		IOPop.setText("I/O Settings");
		jMenu2.add(IOPop);

		jCheckBoxMenuSemaforo.setText("Stoplight");
		jCheckBoxMenuSemaforo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxMenuSemaforoActionPerformed(evt);
			}
		});
		jCheckBoxMenuSegmentDisp.setText("7 Segment Display");
		jCheckBoxMenuSegmentDisp.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxMenuSegmentDispActionPerformed(evt);
			}
		});
		jCheckBoxMenuKeyboard.setText("Hex Keyboard");
		jCheckBoxMenuKeyboard.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxMenuKeyboardActionPerformed(evt);
			}
		});
		jCheckBoxMenuASCII.setText("ASCII Display");
		jCheckBoxMenuASCII.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBoxMenuASCIIActionPerformed(evt);
			}
		});
		jmenuView.setText("View");
		jMenuBar1.add(jmenuView);
		jmenuView.add(jCheckBoxMenuASCII);
		jmenuView.add(jCheckBoxMenuKeyboard);
		jmenuView.add(jCheckBoxMenuSegmentDisp);
		jmenuView.add(jCheckBoxMenuSemaforo);


		jmenuRun.setText("Run");
		jMenuBar1.add(jmenuRun);
		jmenuRun.add(Run);
		Run.setText("Run");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGroup(layout.createSequentialGroup()
												.addComponent(Instrucdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(NextLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(GoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(AsciiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(KeyboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap())
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGap(100, 100, 100)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(R0)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(R0field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(IR)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(IRfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(PC)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(PDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(SP)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(SPfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(0, 0, Short.MAX_VALUE))
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(R6)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(R6field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(R5)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(R5field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(R7)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(R7field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																								.addComponent(R1)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(R1field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(layout.createSequentialGroup()
																								.addComponent(R3)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(R3field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(layout.createSequentialGroup()
																								.addComponent(R4)
																								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(R4field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(R2)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(R2field, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(Cond)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(Condfield, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(SegmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addContainerGap())
														.addGroup(layout.createSequentialGroup()
																.addGap(6, 6, 6)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																				.addComponent(Semaforo0Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGap(18, 18, 18)
																				.addComponent(Semaforo1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addContainerGap())
																		.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup()
												.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(SegmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(Semaforo0Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(Semaforo1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(layout.createSequentialGroup()
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(PDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(PC))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(SPfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(SP))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(IRfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(IR))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R0field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(R0))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R1)
																.addComponent(R1field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R2field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(R2))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R3field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(R3))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R4)
																.addComponent(R4field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R5field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(R5))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R6field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(R6))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(R7field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(R7))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(Condfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(Cond))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(KeyboardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(layout.createSequentialGroup()
														.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(Instrucdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(NextLineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(GoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(AsciiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
		);


		/***********************************JDialog****************************************/
		jDialogIOSettings.setTitle("I/O Memory Allocation");
		jDialogIOSettings.setSize(new java.awt.Dimension(400, 300));
//		SelectMSG.setText("* Values are in Decimal");

		DSemaforo.setText("Semaforo");

		DSegment.setText("7 Segment");

		DAscii.setText("Ascii");

		DKeyboard.setText("Keyboard");
		
		DGoIter.setText("Go Iterations");

		jSpinnerSemaforo.setModel(new javax.swing.SpinnerNumberModel(SemDir, 0, 4095, 1));
		JSpinner.DefaultEditor jSpinnerSemaforoEditoreditor = (JSpinner.DefaultEditor)jSpinnerSemaforo.getEditor();
		JFormattedTextField tfSem = jSpinnerSemaforoEditoreditor.getTextField();
		tfSem.setFormatterFactory(new MyFormatterFactory());

		jSpinnerSegment.setModel(new javax.swing.SpinnerNumberModel(SegDir, 0, 4095, 1));
		JSpinner.DefaultEditor jSpinnerSegmentEditoreditor = (JSpinner.DefaultEditor)jSpinnerSegment.getEditor();
		JFormattedTextField tfSeg = jSpinnerSegmentEditoreditor.getTextField();
		tfSeg.setFormatterFactory(new MyFormatterFactory());

		jSpinnerAscii.setModel(new javax.swing.SpinnerNumberModel(AsciiDir, 0, 4088, 1));
		JSpinner.DefaultEditor jSpinnerAsciiEditoreditor = (JSpinner.DefaultEditor)jSpinnerAscii.getEditor();
		JFormattedTextField tfAscii = jSpinnerAsciiEditoreditor.getTextField();
		tfAscii.setFormatterFactory(new MyFormatterFactory());

		jSpinnerKeyboard.setModel(new javax.swing.SpinnerNumberModel(KeyDir, 0, 4095, 1));
		JSpinner.DefaultEditor jSpinnerKeyboardEditoreditor = (JSpinner.DefaultEditor)jSpinnerKeyboard.getEditor();
		JFormattedTextField tfKey = jSpinnerKeyboardEditoreditor.getTextField();
		tfKey.setFormatterFactory(new MyFormatterFactory());
		jSpinnerGoIter.setModel(new javax.swing.SpinnerNumberModel(GoIter, 1, 100000, 1));


		DialButtonSelect.setText("Select");
		DialButtonSelect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DialButtonSelectActionPerformed(evt);
			}
		});

		DialButtonCancel.setText("Exit");
		DialButtonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DialButtonCancelActionPerformed(evt);
			}
		});


		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialogIOSettings.getContentPane());
		jDialogIOSettings.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(
				jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jDialog1Layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jDialog1Layout.createSequentialGroup()
												.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(DSegment)
														.addComponent(DAscii)
														.addComponent(DKeyboard)
														.addComponent(DSemaforo)
														.addComponent(DGoIter))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jSpinnerSemaforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jSpinnerSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jSpinnerAscii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jSpinnerKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jSpinnerGoIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

												.addGap(0, 0, Short.MAX_VALUE))
										.addGroup(jDialog1Layout.createSequentialGroup()
												.addComponent(DialButtonSelect)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(SelectMSG)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
												.addComponent(DialButtonCancel)))
								.addContainerGap())
		);
		jDialog1Layout.setVerticalGroup(
				jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jDialog1Layout.createSequentialGroup()
								.addGap(39, 39, 39)

								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DSemaforo)
										.addComponent(jSpinnerSemaforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DSegment)
										.addComponent(jSpinnerSegment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DAscii)
										.addComponent(jSpinnerAscii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DKeyboard)
										.addComponent(jSpinnerKeyboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)

								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DGoIter)
										.addComponent(jSpinnerGoIter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)

								.addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DialButtonSelect)
										.addComponent(DialButtonCancel)
										.addComponent(SelectMSG))
								.addContainerGap())
		);




		pack();
	}// </editor-fold>




	private void RunActionPerformed(ActionEvent evt) {
		SetFieldsDefault();
		String Codigo = jTextPane1.getText();
		File Temp = new File("./run.obj");
		WriteFile data = new WriteFile (Temp, false);
		try {
			data.writeToFile(Codigo);//lo importante
		} catch (IOException e) {
			e.printStackTrace();
		}

		FileRead fileRead = new FileRead();
		String text = fileRead.getText(Temp);
		jTextPane1.selectAll();
		jTextPane1.replaceSelection("");
		jTextPane1.setText(text);
		TestFormNuestro Tfn = new TestFormNuestro(Temp);
		Tfn.Run();


		File ffile  = new File("./run.obj");
		Object Text[] = FileRead.getArrayText(ffile);
		main = new Main(ffile);
		TimeCount = 0;
		for (int i=0; i<2048; i++)
			DataXInst[i][1] = Text[i];
		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				DataXInst,
				new String [] {
						"Direccion", "Contenido"
				}
		));

		if(!main.initialize()) {
			String error = "Error in line(s): ";
			for(int p: TestFormNuestro.errores)
				error = error +p+", ";
			Instrucdisplay.setText(error);
			Instrucdisplay.setBackground(Color.ORANGE);
			Instrucdisplay.setEditable(true);
		}
		timeLine.clear();




	}

	private void DialButtonCancelActionPerformed(ActionEvent evt) {
		jDialogIOSettings.setVisible(false);
	}

	private void DialButtonSelectActionPerformed(ActionEvent evt) {
//		SelectMSG.setText("* Values are in Decimal");
		int SemDirtmp = (int) jSpinnerSemaforo.getValue();
		int SegDirtmp = (int) jSpinnerSegment.getValue();
		int AsciiDirtmp = (int) jSpinnerAscii.getValue();
		int KeyDirtmp = (int) jSpinnerKeyboard.getValue();
		GoIter = (int) jSpinnerGoIter.getValue();

		if (!(SegDirtmp ==SemDirtmp|| SegDirtmp == AsciiDirtmp ||SemDirtmp== KeyDirtmp ||SemDirtmp== AsciiDirtmp || SegDirtmp == KeyDirtmp || AsciiDirtmp == KeyDirtmp)){
			SelectMSG.setText("OK!");
			SemDir = SemDirtmp;
			SegDir = SegDirtmp;
			AsciiDir = AsciiDirtmp;
			KeyDir = KeyDirtmp;
//			jTextPane1.setText("SemDir: "+SemDir
//			+"\nSegDir: "+SegDir
//			+"\nAsciiDir: "+AsciiDir
//			+"\nKeyDir: "+KeyDir);
		}
		if (SegDirtmp ==SemDirtmp|| SegDirtmp == AsciiDirtmp ||SemDirtmp== KeyDirtmp ||SemDirtmp== AsciiDirtmp || SegDirtmp == KeyDirtmp || AsciiDirtmp == KeyDirtmp){
			SelectMSG.setText("Directions can't be the same");
		}
		for (int i = AsciiDirtmp; i<(AsciiDirtmp +8); i++){
			if (i==SemDirtmp || i== SegDirtmp || i== KeyDirtmp) {
				SelectMSG.setText("Invalid direction for the Ascii Display");
			}
		}




	}

	private void IOPopActionPerformed(ActionEvent evt) {
		jDialogIOSettings.setVisible(true );
//		SelectMSG.setText("* Values are in Decimal");
		jSpinnerAscii.setValue(AsciiDir);
		jSpinnerKeyboard.setValue(KeyDir);
		jSpinnerSegment.setValue(SegDir);
		jSpinnerSemaforo.setValue(SemDir);
		jSpinnerGoIter.setValue(GoIter);
	}

	private void NextLineActionPerformed(ActionEvent evt) {
		Line();
	}

	public void Line(){

//		int end = timeLine.size();
//		if(TimeCount < end) {
//			Snapshot temp = timeLine.get(TimeCount);
		Snapshot temp = main.run();
		timeLine.add(temp);
		if (main.getMemory()[KeyDir].substring(1).equals("0") && (KeyIn.size()>0)){
			main.toMemory(KeyDir, KeyRead());
		}

//		if (main.getMemory()[KeyDir].equals())

			R1field.setBackground(Color.WHITE);
			R2field.setBackground(Color.WHITE);
			R3field.setBackground(Color.WHITE);
			R4field.setBackground(Color.WHITE);
			R5field.setBackground(Color.WHITE);
			R6field.setBackground(Color.WHITE);
			R7field.setBackground(Color.WHITE);

			//WriteOnDisplay(temp.getRegister());
			R0field.setText(temp.getRegister()[0]);
			R1field.setText(temp.getRegister()[1]);
			R2field.setText(temp.getRegister()[2]);
			R3field.setText(temp.getRegister()[3]);
			R4field.setText(temp.getRegister()[4]);
			R5field.setText(temp.getRegister()[5]);
			R6field.setText(temp.getRegister()[6]);
			R7field.setText(temp.getRegister()[7]);

			Condfield.setText(temp.getCond());

			PDfield.setText(temp.getPc());
			IRfield.setText(temp.getInstructionRegister());
			SPfield.setText(temp.getRegister()[7]);
			Instrucdisplay.setText(temp.getStringToDisplay());
			/*************************************************UPDATE AL SEMAFORO***************************************/

			String ToSem = hexTo4Bit(temp.memory[SemDir].substring(0,1)) + hexTo4Bit(temp.memory[SemDir].substring(1));
			Semaforo(ToSem);
			String ToSeg = hexTo4Bit(temp.memory[SegDir].substring(0,1)) + hexTo4Bit(temp.memory[SegDir].substring(1));
			Segmentdisplay(ToSeg);
		System.out.println("seg- "+ ToSeg + ", Dir -"+SemDir);


		String[] toAscii = new String[8];
			int count = AsciiDir;
			for(int i = 0; i < 8; i++){
				toAscii[i] = temp.memory[count];
				count++;
			}
			Ascii(toAscii);

			//*********************************************************
			if(TimeCount > 0) {
				if(!timeLine.get(TimeCount-1).getRegister()[1].equals(timeLine.get(TimeCount).getRegister()[1]))
					R1field.setBackground(Color.GREEN);
				if(!timeLine.get(TimeCount-1).getRegister()[2].equals(timeLine.get(TimeCount).getRegister()[2]))
					R2field.setBackground(Color.GREEN);
				if(!timeLine.get(TimeCount-1).getRegister()[3].equals(timeLine.get(TimeCount).getRegister()[3]))
					R3field.setBackground(Color.GREEN);
				if(!timeLine.get(TimeCount-1).getRegister()[4].equals(timeLine.get(TimeCount).getRegister()[4]))
					R4field.setBackground(Color.GREEN);
				if(!timeLine.get(TimeCount-1).getRegister()[5].equals(timeLine.get(TimeCount).getRegister()[5]))
					R5field.setBackground(Color.GREEN);
				if(!timeLine.get(TimeCount-1).getRegister()[6].equals(timeLine.get(TimeCount).getRegister()[6]))
					R6field.setBackground(Color.GREEN);
				if(!timeLine.get(TimeCount-1).getRegister()[7].equals(timeLine.get(TimeCount).getRegister()[7]))
					R7field.setBackground(Color.GREEN);

				Object Text[] = temp.memory; // verificar pos de esto chris
				for (int i=0; i<4096; i++) {
					Data[i][1] = Text[i];
				}
				for (int i=0;i<2048;i++) {
					DataXInst[i][1] = Data[i*2][1] + (String)Data[(i*2)+1][1];
				}

				jTable1.setModel(new javax.swing.table.DefaultTableModel(
						DataXInst,
						new String [] {
								"Direccion", "Contenido"
						}
				));
			}
			TimeCount++;
		}



	private void SaveStateActionPerformed(ActionEvent evt) {
		SaveFile.setDialogTitle("Save State");
		int returnVal = SaveFile.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File fileToSave = SaveFile.getSelectedFile();
			WriteFile data = new WriteFile (fileToSave, false);
			try {
				data.writeToFile("RO - "+timeLine.get(TimeCount).getRegister()[0] +
						"\nR1 - "+timeLine.get(TimeCount).getRegister()[1] +
						"\nR2 - "+timeLine.get(TimeCount).getRegister()[2] +
						"\nR3 - "+timeLine.get(TimeCount).getRegister()[3] +
						"\nR4 - "+timeLine.get(TimeCount).getRegister()[4] +
						"\nR5 - "+timeLine.get(TimeCount).getRegister()[5] +
						"\nR6 - "+timeLine.get(TimeCount).getRegister()[6] +
						"\nR7 - "+timeLine.get(TimeCount).getRegister()[7] );//lo importante***** muestra un R7 diferente al que guarda
			} catch (IOException e) {
				e.printStackTrace();
			}


		} else {
			System.out.println("File access cancelled by user.");
		}
	}

	private void GOActionPerformed(ActionEvent evt) {
		int count = 0;
		while (count < GoIter){
			Line();
			System.out.println("Run #"+count);
			count++;
		}

	}


	private void jMenuLoadActionPerformed(java.awt.event.ActionEvent evt) { // eliminar que corra, que solo lo haga run.....done.....
		SetFieldsDefault();
		int returnVal = fileChooser.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = fileChooser.getSelectedFile();
			FileRead fileRead = new FileRead();
			String text = fileRead.getText(file);
			jTextPane1.selectAll();
			jTextPane1.replaceSelection("");
			jTextPane1.setText(text);


		} else {
			System.out.println("File access cancelled by user.");
		}

	}


	private void jMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {
		int returnVal = SaveFile.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File fileToSave = SaveFile.getSelectedFile();
			WriteFile data = new WriteFile (fileToSave, false);
			try {
				data.writeToFile(jTextPane1.getText());//lo importante
			} catch (IOException e) {
				e.printStackTrace();
			}


		} else {
			System.out.println("File access cancelled by user.");
		}
	}

	/*****************************************View checkbox Actions****************************************************/

	private void jCheckBoxMenuKeyboardActionPerformed(java.awt.event.ActionEvent evt) {
		if (jCheckBoxMenuKeyboard.getState() == false)
			KeyboardPanel.setVisible(false);
		else
			KeyboardPanel.setVisible(true);
	}
	private void jCheckBoxMenuSemaforoActionPerformed(java.awt.event.ActionEvent evt) {
		if (jCheckBoxMenuSemaforo.getState()==false) {
			Semaforo0Panel.setVisible(false);
			Semaforo1Panel.setVisible(false);
		}else{
			Semaforo1Panel.setVisible(true);
			Semaforo0Panel.setVisible(true);
		}
	}
	private void jCheckBoxMenuSegmentDispActionPerformed(java.awt.event.ActionEvent evt) {
		if (jCheckBoxMenuSegmentDisp.getState()==false)
			SegmentPanel.setVisible(false);
		else
			SegmentPanel.setVisible(true);
	}
	private void jCheckBoxMenuASCIIActionPerformed(java.awt.event.ActionEvent evt) {
		if (jCheckBoxMenuASCII.getState()==false)
			AsciiPanel.setVisible(false);
		else
			AsciiPanel.setVisible(true);
	}


	/*********************HexKeyboard*******************************************************/
	private void Button0ActionPerformed(ActionEvent evt) {
		KeyWrite("0");
	}
	private void Button1ActionPerformed(ActionEvent evt) {
		KeyWrite("1");
	}
	private void Button2ActionPerformed(ActionEvent evt) {
		KeyWrite("2");
	}
	private void Button3ActionPerformed(ActionEvent evt) {
		KeyWrite("3");
	}
	private void Button4ActionPerformed(ActionEvent evt) {
		KeyWrite("4");
	}
	private void Button5ActionPerformed(ActionEvent evt) {
		KeyWrite("5");
	}
	private void Button6ActionPerformed(ActionEvent evt) {
		KeyWrite("6");
	}
	private void Button7ActionPerformed(ActionEvent evt) {
		KeyWrite("7");
	}
	private void Button8ActionPerformed(ActionEvent evt) {
		KeyWrite("8");
	}
	private void Button9ActionPerformed(ActionEvent evt) {
		KeyWrite("9");
	}
	private void ButtonAActionPerformed(ActionEvent evt) {
		KeyWrite("A");
	}
	private void ButtonBActionPerformed(ActionEvent evt) {
		KeyWrite("B");
	}
	private void ButtonCActionPerformed(ActionEvent evt) {
		KeyWrite("C");
	}
	private void ButtonDActionPerformed(ActionEvent evt) {
		KeyWrite("D");
	}
	private void ButtonEActionPerformed(ActionEvent evt) {
		KeyWrite("E");
	}
	private void ButtonFActionPerformed(ActionEvent evt) {
		KeyWrite("F");
	}



	public static void WriteOnDisplay(String[] R){
		R1field.setText(R[1]);
		R2field.setText(R[2]);
		R3field.setText(R[3]);
		R4field.setText(R[4]);
		R5field.setText(R[5]);
		R6field.setText(R[6]);
		R7field.setText(R[7]);
	}

	public static void SetFieldsDefault(){
		SPfield.setText("SP!");
		PDfield.setText("PC!");
		IRfield.setText("IR!");
		R0field.setText("R0!");
		R1field.setText("R1!");
		R2field.setText("R2!");
		R3field.setText("R3!");
		R4field.setText("R4!");
		R5field.setText("R5!");
		R6field.setText("R6!");
		R7field.setText("R7!");
		Instrucdisplay.setText("INSTRUCTION!");
		Instrucdisplay.setBackground(Color.WHITE);
	}


	public void Semaforo(String mem){
		if (mem.substring(6).equals("11")) {
			int count =0;
			while (count<=10) {
				count++;

				if (SemInter) {
					Red0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png"))); // NOI18N
					Yellow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					Green0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					SemInter = false;
				} else if (!SemInter) {
					if (mem.substring(0, 1).equals("0")) {
						Red0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png"))); // NOI18N
					} else
						Red0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/58afdad6829958a978a4a693.png")));
					if (mem.substring(1, 2).equals("0")) {
						Yellow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					} else
						Yellow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_icon.svg.png")));
					if (mem.substring(2, 3).equals("0")) {
						Green0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					} else
						Green0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/600px-Ski_trail_rating_symbol-green_circle.svg.png")));
					if (mem.substring(3, 4).equals("0")) {
						Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					} else
						Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/58afdad6829958a978a4a693.png")));
					if (mem.substring(4, 5).equals("0")) {
						Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					} else
						Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_icon.svg.png")));
					if (mem.substring(5, 6).equals("0")) {
						Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
					} else
						Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/600px-Ski_trail_rating_symbol-green_circle.svg.png")));
					SemInter = true;
				}

			}
		}
		else
			//if (mem.substring(6).equals("00"))
			{
				if (mem.substring(0, 1).equals("0")) {
					Red0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png"))); // NOI18N
				} else
					Red0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/58afdad6829958a978a4a693.png")));
				if (mem.substring(1, 2).equals("0")) {
					Yellow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
				} else
					Yellow0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_icon.svg.png")));
				if (mem.substring(2, 3).equals("0")) {
					Green0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
				} else
					Green0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/600px-Ski_trail_rating_symbol-green_circle.svg.png")));
				if (mem.substring(3, 4).equals("0")) {
					Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
				} else
					Red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/58afdad6829958a978a4a693.png")));
				if (mem.substring(4, 5).equals("0")) {
					Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
				} else
					Yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Yellow_icon.svg.png")));
				if (mem.substring(5, 6).equals("0")) {
					Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Solid_black.png")));
				} else
					Green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/600px-Ski_trail_rating_symbol-green_circle.svg.png")));
		}

	}

	public static void Segmentdisplay(String mem){
		if (mem.substring(7).equals("0")){
			if (mem.substring(0,1).equals("0"))
				Seg0A.setBackground(Color.DARK_GRAY);
			else
				Seg0A.setBackground(Color.RED);
			if (mem.substring(1,2).equals("0"))
				Seg0B.setBackground(Color.DARK_GRAY);
			else
				Seg0B.setBackground(Color.RED);
			if (mem.substring(2,3).equals("0"))
				Seg0C.setBackground(Color.DARK_GRAY);
			else
				Seg0C.setBackground(Color.RED);
			if (mem.substring(3,4).equals("0"))
				Seg0D.setBackground(Color.DARK_GRAY);
			else
				Seg0D.setBackground(Color.RED);
			if (mem.substring(4,5).equals("0"))
				Seg0E.setBackground(Color.DARK_GRAY);
			else
				Seg0E.setBackground(Color.RED);
			if (mem.substring(5,6).equals("0"))
				Seg0F.setBackground(Color.DARK_GRAY);
			else
				Seg0F.setBackground(Color.RED);
			if (mem.substring(6,7).equals("0"))
				Seg0G.setBackground(Color.DARK_GRAY);
			else
				Seg0G.setBackground(Color.RED);

		}
		if (mem.substring(7).equals("1")){
			if (mem.substring(0,1).equals("0"))
				Seg1A.setBackground(Color.DARK_GRAY);
			else
				Seg1A.setBackground(Color.RED);
			if (mem.substring(1,2).equals("0"))
				Seg1B.setBackground(Color.DARK_GRAY);
			else
				Seg1B.setBackground(Color.RED);
			if (mem.substring(2,3).equals("0"))
				Seg1C.setBackground(Color.DARK_GRAY);
			else
				Seg1C.setBackground(Color.RED);
			if (mem.substring(3,4).equals("0"))
				Seg1D.setBackground(Color.DARK_GRAY);
			else
				Seg1D.setBackground(Color.RED);
			if (mem.substring(4,5).equals("0"))
				Seg1E.setBackground(Color.DARK_GRAY);
			else
				Seg1E.setBackground(Color.RED);
			if (mem.substring(5,6).equals("0"))
				Seg1F.setBackground(Color.DARK_GRAY);
			else
				Seg1F.setBackground(Color.RED);
			if (mem.substring(6,7).equals("0"))
				Seg1G.setBackground(Color.DARK_GRAY);
			else
				Seg1G.setBackground(Color.RED);

		}
	}

	public static void Ascii( String[] mem){// son en hex
		String tmp;
		int n;

		n = Integer.valueOf(mem[0], 16);
		Hex1.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[1], 16);
		Hex2.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[2], 16);
		Hex3.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[3], 16);
		Hex4.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[4], 16);
		Hex5.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[5], 16);
		Hex6.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[6], 16);
		Hex7.setText(String.valueOf((char) n));
		n = Integer.valueOf(mem[7], 16);
		Hex8.setText(String.valueOf((char) n));
	}



	public static void KeyWrite(String key){
		String result;
		result = key +"1";
		if (KeyIn.size()<4) {
			KeyIn.add(result);
		}
		Instrucdisplay.setText("KeyBoard in - " + KeyIn.get(KeyIn.size()-1));
	}
	public static String KeyRead(){
			String result = KeyIn.remove(0);
			return result;
	}



	public static String hexTo4Bit(String s) {
		Map<String,String> map1= new HashMap<String,String>();
		map1.put("0","0000");map1.put("1","0001");map1.put("2","0010");map1.put("3","0011");
		map1.put("4","0100");map1.put("5","0101");map1.put("6","0110");map1.put("7","0111");
		map1.put("8","1000");map1.put("9","1001");map1.put("A","1010");map1.put("B","1011");
		map1.put("C","1100");map1.put("D","1101");map1.put("E","1110");map1.put("F","1111");
		return map1.get(s);
	}

	/*********************************JSpinner*********************************************/


	private static class MyFormatterFactory extends DefaultFormatterFactory {
		public JFormattedTextField.AbstractFormatter getDefaultFormatter() {
			return new HexFormatter();
		}
	}

	private static class HexFormatter extends DefaultFormatter {
		public Object stringToValue(String text) throws ParseException {
			try {
				return Integer.valueOf(text, 16);
			} catch (NumberFormatException nfe) {
				throw new ParseException(text,0);
			}
		}

		public String valueToString(Object value) throws ParseException {
			return Integer.toHexString(
					((Integer)value).intValue()).toUpperCase();
		}
	}


	static String stringToDisplay;
	static ArrayList<Snapshot> timeLine = new ArrayList<>();
	static int TimeCount;
	static ArrayList<String> KeyIn = new ArrayList<>();




	// Variables declaration - do not modify
	private javax.swing.JFileChooser fileChooser;
	private javax.swing.JFileChooser SaveFile;



	private javax.swing.JButton Button0;
	private javax.swing.JButton Button6;
	private javax.swing.JButton Button1;
	private javax.swing.JButton Button2;
	private javax.swing.JButton Button4;
	private javax.swing.JButton Button5;
	private javax.swing.JButton Button3;
	private javax.swing.JButton Button7;
	private javax.swing.JButton Button8;
	private javax.swing.JButton Button9;
	private javax.swing.JButton ButtonA;
	private javax.swing.JButton ButtonB;
	private javax.swing.JButton ButtonC;
	private javax.swing.JButton ButtonD;
	private javax.swing.JButton ButtonE;
	private javax.swing.JButton ButtonF;
	private static javax.swing.JLabel Green0;
	private static javax.swing.JLabel Green3;
	private static javax.swing.JTextField Hex1;
	private static javax.swing.JTextField Hex2;
	private static javax.swing.JTextField Hex3;
	private static javax.swing.JTextField Hex4;
	private static javax.swing.JTextField Hex5;
	private static javax.swing.JTextField Hex6;
	private static javax.swing.JTextField Hex7;
	private static javax.swing.JTextField Hex8;
	private javax.swing.JLabel IR;
	private static javax.swing.JTextField IRfield;
	private static javax.swing.JTextField Instrucdisplay;
	private javax.swing.JLabel PC;
	private static javax.swing.JTextField PDfield;
	private javax.swing.JLabel R0;
	private static javax.swing.JTextField R0field;
	private javax.swing.JLabel R1;
	private static javax.swing.JTextField R1field;
	private javax.swing.JLabel R2;
	private static javax.swing.JTextField R2field;
	private javax.swing.JLabel R3;
	private static javax.swing.JTextField R3field;
	private javax.swing.JLabel R4;
	private  static javax.swing.JTextField R4field;
	private javax.swing.JLabel R5;
	private  static javax.swing.JTextField R5field;
	private javax.swing.JLabel R6;
	private static javax.swing.JTextField R6field;
	private javax.swing.JLabel R7;
	private static javax.swing.JTextField R7field;
	private static javax.swing.JLabel Red0;
	private static javax.swing.JLabel Red3;
	private static javax.swing.JLabel SP;
	private static javax.swing.JTextField SPfield;
	private static javax.swing.Box.Filler Seg0A;
	private static javax.swing.Box.Filler Seg0B;
	private static javax.swing.Box.Filler Seg0C;
	private static javax.swing.Box.Filler Seg0D;
	private static javax.swing.Box.Filler Seg0E;
	private static javax.swing.Box.Filler Seg0F;
	private static javax.swing.Box.Filler Seg0G;
	private static javax.swing.Box.Filler Seg1A;
	private static javax.swing.Box.Filler Seg1B;
	private static javax.swing.Box.Filler Seg1C;
	private static javax.swing.Box.Filler Seg1D;
	private static javax.swing.Box.Filler Seg1E;
	private static javax.swing.Box.Filler Seg1F;
	private static javax.swing.Box.Filler Seg1G;
	private static javax.swing.JLabel Yellow0;
	private static javax.swing.JLabel Yellow3;
	private javax.swing.JButton NextLineButton;
	private javax.swing.JButton GoButton;
	private javax.swing.JMenu jMenuFile;
	private javax.swing.JMenu jMenu2;

	private javax.swing.JTextField Condfield;
	private javax.swing.JLabel Cond;


	private javax.swing.JMenu jmenuView;
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuKeyboard;
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuASCII;
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuSemaforo;
	private javax.swing.JCheckBoxMenuItem jCheckBoxMenuSegmentDisp;



	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel AsciiPanel;
	private javax.swing.JPanel KeyboardPanel;
	private javax.swing.JPanel SegmentPanel;
	private javax.swing.JPanel Semaforo0Panel;
	private javax.swing.JPanel Semaforo1Panel;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jTable1;

	private javax.swing.JScrollPane TextPanel;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JPanel jPanel1;

	private javax.swing.JMenu jmenuRun;
	private javax.swing.JMenuItem IOPop;
	private javax.swing.JMenuItem Run;

	/********initial directions************/
	int SemDir = 0;
	int SegDir = 1;
	int AsciiDir = 3;
	public static int KeyDir = 2;

	int GoIter = 500;
	/**********JDialog***********/
	private javax.swing.JSpinner jSpinnerAscii;
	private javax.swing.JSpinner jSpinnerKeyboard;
	private javax.swing.JSpinner jSpinnerSegment;
	private javax.swing.JSpinner jSpinnerSemaforo;
	private javax.swing.JSpinner jSpinnerGoIter;
	private javax.swing.JLabel DAscii;
	private javax.swing.JLabel DKeyboard;
	private javax.swing.JLabel DSegment;
	private javax.swing.JLabel DSemaforo;
	private javax.swing.JLabel DGoIter;
	private javax.swing.JButton DialButtonCancel;
	private javax.swing.JButton DialButtonSelect;
	private javax.swing.JLabel SelectMSG;
	private javax.swing.JDialog jDialogIOSettings;

	private javax.swing.JEditorPane jEditorPane1;
	private javax.swing.JTextPane jTextPane1;

	private Main main;
	private boolean SemInter = false;




	private javax.swing.JMenuItem jMenuSaveState;
	Object Data [][] = new Object[4096][2];
	Object DataXInst [][] = new Object[2048][2];
	// End of variables declaration
}
